import json
import sys
import os.path

sys.path.insert(1, "/home/abramov/ASB-Project")
from scripts.HELPERS.paths import ploidy_dict_path, parallel_parameters_path

out_path = parallel_parameters_path + 'PE_parameters.cfg'

good_boys = ['A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS823UOD_',
             'A549_lung_carcinoma!_labs_richard-myers___biosamples_ENCBS164AAA_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS924DBS_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS352MRW_',
             'HCT-116_colon_carcinoma!GSE78064',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS407BKP_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS404RGH_',
             'A549_lung_carcinoma!_labs_vishwanath-iyer___biosamples_ENCBS162AAA_',
             'MV4-11_childhood_acute_monocytic_leukemia!GSE88746',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS909XAR_',
             'A549_lung_carcinoma!_labs_richard-myers___biosamples_ENCBS423ENC_',
             'HCT-116_colon_carcinoma!_labs_michael-snyder___biosamples_ENCBS626JHZ_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS643ZJW_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS809MNA_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS737LUY_',
             'RCH-ACV_B_acute_lymphoblastic_leukemia_with_t1;19q23;p13.3_E2A-PBX1_TCF3-PBX1!GSE83671',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS024QOG_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS994WPS_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS274ZVG_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS802OFY_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS479IGH_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS465PUD_',
             'HCT-116_colon_carcinoma!_labs_richard-myers___biosamples_ENCBS389ENC_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS697XFI_',
             'SK-N-SH_neuroblastoma!GSE76815',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS378AAA_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS278VLL_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS344LIE_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS293ZDP_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS207UAM_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS307SRO_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS118YJZ_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS125ACM_',
             'K562_myelogenous_leukemia!GSE24777',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS860ULO_',
             'DOHH2_diffuse_large_B-cell_lymphoma!GSE101017',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS477GCU_',
             'LoVo_colorectal_adenocarcinoma!None',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS141HBH_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS582CLM_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS745PHH_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS839CNN_',
             'SK-N-SH_neuroblastoma!GSE90682',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS044UVO_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS491KZL_',
             'HCT-116_colon_carcinoma!GSE50610',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS136ZVQ_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS514LZY_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS792ASV_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS603CUX_',
             'Kasumi-1_childhood_acute_myeloid_leukemia_with_maturation!GSE60130',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS357NWO_',
             'MDA-MB-453_breast_adenocarcinoma!GSE45201',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS711SCS_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS362JCG_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS288EEL_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS397AAA_',
             'MV4-11_childhood_acute_monocytic_leukemia!GSE83671',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS358PMO_',
             'K562_myelogenous_leukemia!_labs_richard-myers___biosamples_ENCBS316CKF_',
             'K562_myelogenous_leukemia!_labs_richard-myers___biosamples_ENCBS109ENC_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS238VUA_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS922MBD_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS588OSJ_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS758URS_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS710NDE_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS377AAA_',
             'Reh_ATCC_CRL-8286!GSE102785',
             '22RV1_prostate_carcinoma!_labs_michael-snyder___biosamples_ENCBS822DIG_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS059GTH_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS626VGF_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS472FTV_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS101QRF_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS484NJJ_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS032EMA_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS685FEM_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS406RFF_',
             'HCT-116_colon_carcinoma!_labs_michael-snyder___biosamples_ENCBS615KTO_',
             'OCI-LY7_diffuse_large_B-cell_lymphoma!GSE100977',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS613WNR_',
             'SK-N-SH_neuroblastoma!_labs_bradley-bernstein___biosamples_ENCBS324TZB_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS407XHO_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS351GWD_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS114PSH_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS094BQG_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS048GNZ_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS901YZG_',
             'K562_myelogenous_leukemia!_labs_xiang-dong-fu___biosamples_ENCBS074NGX_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS320BUL_',
             'HCT-116_colon_carcinoma!_labs_bradley-bernstein___biosamples_ENCBS494OPB_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS255OGK_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS727RLP_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS041GBQ_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS820SVQ_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS443AAA_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS329VDX_',
             'K562_myelogenous_leukemia!_labs_kevin-white___biosamples_ENCBS061XWL_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS850QNJ_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS726LXJ_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS756YTM_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS686ZWW_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS047ROF_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS185MQS_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS783WYV_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS966VII_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS576ESJ_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS543YEP_',
             'THP-1_acute_monocytic_leukemia!GSE79899',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS719UQU_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS168IFT_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS395TGI_',
             'SK-N-SH_neuroblastoma!_labs_bradley-bernstein___biosamples_ENCBS500EWH_',
             'D283_Med_medulloblastoma!GSE92582',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS555SMT_',
             'SK-N-SH_neuroblastoma!_labs_michael-snyder___biosamples_ENCBS061YYT_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS340RXI_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS321WEQ_',
             'K562_myelogenous_leukemia!_labs_kevin-white___biosamples_ENCBS105ZBV_',
             'K562_myelogenous_leukemia!_labs_richard-myers___biosamples_ENCBS577JGM_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS663MZB_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS465MWC_',
             'DOHH2_diffuse_large_B-cell_lymphoma!_labs_bradley-bernstein___biosamples_ENCBS662OGM_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS002UWD_',
             'SK-N-SH_neuroblastoma!_labs_michael-snyder___biosamples_ENCBS376ENC_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS983ZXV_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS232KKV_',
             'K562_myelogenous_leukemia!_labs_xiang-dong-fu___biosamples_ENCBS267LNH_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS153NPL_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS714GDR_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS906KIP_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS386HKI_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS944BMM_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS721MSZ_',
             'K562_myelogenous_leukemia!_labs_michael-snyder___biosamples_ENCBS584ZNF_',
             'K562_myelogenous_leukemia!_labs_bradley-bernstein___biosamples_ENCBS639AAA_',
             'A549_lung_carcinoma!_labs_tim-reddy___biosamples_ENCBS608SQG_',
             '22RV1_prostate_carcinoma!_labs_michael-snyder___biosamples_ENCBS626QQL_']

if __name__ == "__main__":
    with open(ploidy_dict_path, 'r') as read_file:
        d = json.loads(read_file.readline())
    keys = sorted(d.keys())
    with open(out_path, 'w') as file:
        for key in keys:

            if key not in good_boys:
                continue

            is_empty = True
            for value in d[key]:
                if os.path.isfile(value):
                    is_empty = False
            if is_empty:
                continue
            file.write(key + '\n')
